# -*- coding: utf-8 -*-
"""Down_arriv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eT06xcFkeMIOhTA1Hxc0DLnxnPWlo81s
"""

# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rfPtnjvQWTrS6d4o0w3zhgRUdfZ8p9wP
"""

import matplotlib.pyplot as plt
import csv
import numpy as np
uplinkdata=0
downlinkdata=0
noofuplinkpackets=0
noofdownlinkpackets=0
timeatwhichpacketarries=[]
timeatwhichpacketisend=[]
interdelayinarrival=[]
interdelayinsend=[]


with open('./norm_cas_mob_recv', mode='r') as infile:
    reader = csv.reader(infile)
    for column in reader:
        noofdownlinkpackets = noofdownlinkpackets + 1
        downlinkdata=downlinkdata+int(column[5])
        timeatwhichpacketarries.append("{:.2f}".format(float(column[1])))

lengthoflistfpacketarrival=len(timeatwhichpacketarries)
for i in range(lengthoflistfpacketarrival-1):
    interdelayinarrival.append(float("{:.2f}".format(float(timeatwhichpacketarries[i+1])-float(timeatwhichpacketarries[i]))))


print("\nNo of DownLink Packets\n", noofdownlinkpackets)
print("\nDownLink Data\n", downlinkdata," Bytes")

print('\nTotal DownLink Throughput \n', downlinkdata/8,"Bytes/sec")
print('\nTime at which packet arrive \n',timeatwhichpacketarries)


print('\nInterDelay in packet arrival \n',interdelayinarrival, " secs ")

print('\nAverage downlink interdelay\n', sum(interdelayinarrival)/noofdownlinkpackets, " secs ")

print('\nST dev downlink\n', np.std(interdelayinarrival,ddof=1))

summ=0.0
cdfinterdelayinarrival=[]
for i in interdelayinarrival:
  summ=summ+i
  cdfinterdelayinarrival.append(summ)
print('\CDFnInterDelay in packet arrival \n',cdfinterdelayinarrival, " secs ")

print('\CDF 100 \n',cdfinterdelayinarrival[100])

modifiedarrivaltime=[]

# arrival
for i in range(1,len(timeatwhichpacketarries)):
    modifiedarrivaltime.append(i)


plt.bar(modifiedarrivaltime,cdfinterdelayinarrival)
plt.xlabel('Number of packets')
plt.ylabel('Interdelay in sec')

plt.legend([' Inter delay between downlink packets'])
plt.show()

